#!/bin/bash

# Set the bspwm socket location
hash bspwm 2>/dev/null && export BSPWM_SOCKET="$XDG_RUNTIME_DIR/bswpm-socket"

# Specify many application config paths
hash gimp       2>/dev/null && export GIMP2_DIRECTORY="$XDG_CONFIG_HOME/gimp-2.8"
hash virtualbox 2>/dev/null && export  VBOX_USER_HOME="$XDG_CONFIG_HOME/virtualbox"
hash mplayer    2>/dev/null && export    MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
hash vagrant    2>/dev/null && export    VAGRANT_HOME="$XDG_CONFIG_HOME/vagrant"
hash mpv        2>/dev/null && export        MPV_HOME="$XDG_CONFIG_HOME/mpv"

# History file locations
hash mysql 2>/dev/null && export MYSQL_HISTFILE="$XDG_CACHE_HOME/mysql_history"

# OpenGL NVIDIA shader cache directory
[ -e /usr/lib/modprobe.d/nvidia.conf ] && export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME"

# Put chromiums cache in /tmp for better performance
hash chromium 2>/dev/null && export CHROMIUM_USER_FLAGS="--disk-cache-dir=/tmp/chrome-cache --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so"

# MPD runs on my default, this makes other mpd related things more portable
export MPC_HOST=htpc
