#!/bin/bash

# Set the bspwm socket location
hash bspwm 2>/dev/null && export BSPWM_SOCKET="$XDG_RUNTIME_DIR/bswpm-socket"

# Always install ruby gems local to the user
if hash gem 2>/dev/null
then
    export GEMRC="$XDG_CONFIG_HOME/gemrc/config"
    export GEM_HOME="$HOME/.local/lib/ruby/gems/$(ruby -e 'puts RbConfig::CONFIG["ruby_version"]')"
    export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem/specs"
    export PATH="$PATH:$GEM_HOME/bin"
fi

# nodejs's NPM tool configuration
if hash npm 2>/dev/null
then
    export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
    export PATH="$PATH:$HOME/.local/lib/nodejs/bin"
fi

# Specify many application config paths
hash http       2>/dev/null && export HTTPIE_CONFIG_DIR="$XDG_CONFIG_HOME/httpie"
hash gimp       2>/dev/null && export   GIMP2_DIRECTORY="$XDG_CONFIG_HOME/gimp-2.8"
hash virtualbox 2>/dev/null && export    VBOX_USER_HOME="$XDG_CONFIG_HOME/virtualbox"
hash mplayer    2>/dev/null && export      MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
hash mpv        2>/dev/null && export          MPV_HOME="$XDG_CONFIG_HOME/mpv"

# Specify many application data paths
hash vagrant 2>/dev/null && export   VAGRANT_HOME="$XDG_DATA_HOME/vagrant"
hash berks   2>/dev/null && export BERKSHELF_PATH="$XDG_DATA_HOME/berkshelf"

# OpenGL NVIDIA shader cache directory
[ -e /usr/lib/modprobe.d/nvidia.conf ] && export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME"

# Put chromiums cache in /tmp for better performance
hash chromium 2>/dev/null && export CHROMIUM_USER_FLAGS="--disk-cache-dir=/tmp/chrome-cache --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so"

# MPD runs on my default, this makes other mpd related things more portable
export MPD_HOST=htpc
