[addressbooks]
[[icloud]]
path = /mnt/documents/contacts/icloud/

[general]
default_action = list
editor = vim, -i, NONE
merge_editor = vimdiff

[contact table]
display = first_name
group_by_addressbook = no
reverse = no
show_nicknames = no
show_uids = yes
sort = last_name
localize_dates = yes
preferred_phone_number_type = pref, cell, home
preferred_email_address_type = pref, work, home

[vcard]
search_in_source_files = no
skip_unparsable = no
