#!/bin/bash

source "$HOME/.config/bash/environment"

if systemctl -q is-active user-session@$USER
then
	# Default systemd to the console target
	target="console"

	# If we're logging in from VT1 start the graphical target
	if [[ $XDG_VTNR == 1 ]] && ! systemctl --user -q is-active graphical.target &> /dev/null
	then
		target="graphical"
	fi

	# Bring up systemd --user to the specified target
	systemctl --user start ${target}.target

	# Exit the VT
	[[ $target == "graphical" ]] && clear && logout
fi

source "$HOME/.bashrc"
