#!/bin/bash

source "$HOME/.config/bash/environment"

# Populate systemd environment
systemctl --user import-environment

# Default systemd to the console target
target="console"

# If we're logging in from VT1 start the graphical target
if [[ $XDG_VTNR == 1 ]] && ! systemctl --user -q is-active graphical.target &> /dev/null
then
	target="graphical"
fi

# Prompt to unlock ssh-key
systemctl --user start ssh-agent
ssh-add

# Bring up systemd --user to the specified target
systemctl --user start ${target}.target

# Keep the session alive with minimal memory consumption
[[ $target == "graphical" ]] && clear && exec sleep infinity

source "$HOME/.bashrc"
