#!/bin/bash

source "$HOME/.config/bash/environment"

# Default systemd to the console target
target="console"

# If we're logging in from VT1 start the graphical target
if [[ $XDG_VTNR == 1 ]] && ! systemctl --user -q is-active graphical.target &> /dev/null
then
	target="graphical"
fi

# Bring up systemd --user to the specified target
systemctl --user import-environment
systemctl --user start ${target}.target

[[ $target == "graphical" ]] && clear && exec sleep infinity

source "$HOME/.bashrc"
