#!/usr/bin/env bash

# Use bash completion
if [[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]]; then
	# Do not egar load completions from the compatability directory. This
	# SIGNIFICANTLY speeds up bash completion loading.
	#
	# See bashrc.install for automatic linking
	BASH_COMPLETION_COMPAT_DIR=/dev/null

	progress_timer "load bash-completion" source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
fi
