#!/usr/bin/env bash

# Use bash completion
if [[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]]; then
	# Do not egar load completions from the compatability directory. This
	# SIGNIFICANTLY speeds up bash completion loading.
	#
	# See bashrc.install for automatic linking
	BASH_COMPLETION_COMPAT_DIR=/dev/null

	progress_timer "load bash-completion" source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
fi

# Setup homebrew auto update if it isn't already
if hash brew 2>/dev/null && ! launchctl list | grep -q homebrew-autoupdate; then
	mkdir -p "${HOME}/Library/LaunchAgents"
	brew autoupdate start 3600 --cleanup
fi
