#!/usr/bin/env bash

vim-singleton()
{
  # If we don't have neovim default to vim
  hash nvim 2>/dev/null || /usr/bin/vim "$@"

  # Check if vim is already running
  vim_id="$(jobs | sed -n "/nvim/s/\[\([0-9]\)\]+.*/\1/p")"

  export NVIM_LISTEN_ADDRESS=/tmp/nvim.socket

  # No instance of nvim running. Start nvim and provide a server socket address
  # to communicate for future calls to this script.
  if [[ ! "$vim_id" ]]
  then
    nvim "$@"
    return 0
  fi

  # We can only open the file in the active vim session with nvr (neovim-remote)
  if ! hash nvr 2>/dev/null
  then
    echo "Refusing to start a new instance of nvim" >&2
    echo "pip3 install neovim-remote to automatically open files in the existing instance"
    return 1
  fi

  # Open file in active vim session. Wrap in a subshell to avoid job control
  # messages and background the job. nvr will wait until nvim responds, which
  # will only happen once it's in the forground.
  (nvr --nostart "$@" &)

  fg "$vim_id"
}
