#!/usr/bin/env bash

vim-singleton() {
	# If we don't have neovim default to vim
	hash nvim 2>/dev/null || /usr/bin/vim "$@"

	# Check if vim is already running
	vim_id="$(jobs | sed -n "/nvim/s/\[\([0-9]\)\]+.*/\1/p")"

	export NVIM_LISTEN_ADDRESS=/tmp/nvim-${TMUX_PANE:-notmux}.socket

	# No instance of nvim running. Start nvim and provide a server socket address
	# to communicate for future calls to this script.
	if [[ ! "$vim_id" ]]; then
		# Ensure we don't have an invalid socket address
		rm -f $NVIM_LISTEN_ADDRESS
		nvim --listen $NVIM_LISTEN_ADDRESS "$@"
		return 0
	fi

	# Open passed files
	if [[ "$@" != "" ]]; then
		local files=()

		# File list must be absolute path, since vims current directory may be
		# different from where we are in the shell
		for path in "$@"; do
			files+=("$(realpath $(dirname "$path"))/$(basename "$path")")
		done

		nvim --server $NVIM_LISTEN_ADDRESS --remote "${files[@]}"
	fi

	fg "$vim_id"
}
