tap "evanpurkhiser/personal"
tap "homebrew/cask-fonts"


cask "1password"
cask "alacritty"
cask "cron"
cask "discord"
cask "figma"
cask "google-chrome"
cask "hammerspoon"
cask "karabiner-elements"
cask "notion"
cask "numi"
cask "pixelsnap"
cask "raycast"
cask "slack"
cask "tailscale"
cask "telegram"
cask "font-caskaydia-cove-nerd-font"
cask "cloudflare-warp"

# Basic terminal stuff
brew "bash"
brew "bash-completion"
brew "coreutils"

# Terminal window managment
brew "tmux"
brew "reattach-to-user-namespace"

# Tooling
brew "entr"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "htop"
brew "imagemagick"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "rsync"
brew "shfmt"
brew "tree"
brew "wget"
brew "gh"

# Languages, runtimes, compilers
brew "cmake"
brew "go"
brew "node"
brew "python"
brew "ruby"
brew "sqlite"

# Dependency managment
brew "pyenv"
brew "volta"
brew "direnv"
brew "yarn"
