#!/bin/sh

# Configuration
bspc config split_ratio               0.5
bspc config border_width              2
bspc config window_gap                10
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config auto_cancel               true
bspc config honor_size_hints          true
bspc config click_to_focus            true

bspc config normal_border_color       "#5E7175"
bspc config focused_border_color      "#37BF8D"

# Setup destkops
bspc monitor ^1 -d $(seq 1 9)
bspc monitor ^2 -d $(seq 1 2)

# Set the root cursor
xsetroot -cursor_name left_ptr

# Adopt any ophan windows
bspc control --adopt-orphans

# Always float chrome chat windows
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd state=floating
bspc rule -a mpv state=floating
