#!/bin/sh

FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS

bspc rule -a Gimp -d Eight --floating

bspc config split_ratio               0.52
bspc config border_width              4
bspc config window_gap                10
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config auto_cancel               true

# Set the root cursor
xsetroot -cursor_name left_ptr

# Adopt any ophan windows
bspc control --adopt-orphans
