t_status="bg=#3C3836"
t_border="fg=#3C3836"
t_msg="bg=#fe8819,fg=#1d2021"

t_window_name="fg=#fbf1c7,bg=#32302f"
t_window_num="fg=#ebdbb2,bg=#504945"
t_window_flags="fg=#665c54"
t_window_flag_bell="fg=#FFD800"

t_window_active_name="fg=#ffffff,bg=#282828"
t_window_active_num="fg=#ffffff,bg=#cc241d"
t_window_active_flags="fg=#fe8019"

t_clock="bg=#fe8819,fg=#1d2021"

t_indicator_copy="bg=brightyellow,fg=black"
t_indicator_prefix="bg=blue,fg=brightwhite"
t_indicator_locked="bg=red,fg=brightwhite"

t_pane_title_active="fg=#ffffff,bg=#cc241d"
t_pane_title_active_edge="fg=#cc241d"
t_pane_title_inactive="fg=#928374,bg=#3C3836"
t_pane_title_inactive_edge="fg=#3C3836"
t_pane_title_text="fg=#ebdbb2,bg=#3C3836"
t_pane_title_transition="fg=#cc241d,bg=#3C3836"
