#!/bin/bash

# Open a PR from the current commit
git-pr()
{
    git rev-parse || return 1

    # Use the ticket number if possible as the branch name
    local branch=$(git show -q --format=%b \
        | grep ^Jira \
        | sed -re 's/^Jira: (.+)/\1/g;s/, ?/-/g' \
        | tr -dc '[:print:]')

    # Use the commit message as a branch name if no ticket number
    # Remove special characters and use dashes for spaces
    if [[ $branch == "none" ]]
    then
        branch=$(git show -q --format=%s | sed -re 's/[^0-9a-zA-Z ]//g;s/ /-/g' | tr -dc '[:print:]')
    fi

    # Branch name should be all lowercase
    branch=$(echo $branch | perl -ne 'print lc')

    echo "Opening pull-request from remote branch ${branch}"

    git push origin ${1-@}:refs/heads/${branch}
    hub pull-request -fh ${branch} -a ${} | tee | nc localhost 2224
}
