#!/usr/bin/env bash

read -r -d '' __fzf_pr_script <<'EOF'
import os
import yaml
import requests
import subprocess

hub_file = os.path.expandvars("$XDG_CONFIG_HOME/hub")
hub_token = yaml.load(open(hub_file, 'r').read())['github.com'][0]['oauth_token']

try:
    repo = subprocess.check_output(['git', 'config', '--get', 'remote.origin.url'], encoding='utf8') \
        .split(':')[1] \
        .strip()
except subprocess.CalledProcessError:
    exit(0)

r = requests.get(
    f'https://api.github.com/repos/{repo}/pulls?sort=created&direction=desc',
    headers={'Authentication': f'Bearer {hub_token}'}
)

for k, v in [(d['head']['ref'], d['title']) for d in r.json() if d['user']['login'] == 'EvanPurkhiser']:
    print(k, '\t', v)
EOF

fzf-pr-widget() {
    local selected="$(python3 -c "$__fzf_pr_script" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS" fzf --with-nth=2.. -m "$@" | cut -f1)"
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
}

bind -x '"\C-g": "fzf-pr-widget"'
