#!/usr/bin/env bash

alias sudo="sudo -E " # carry over environment to sudo commands
alias cp="cp -i"      # confirm before overwriting something
alias mv="mv -i"      # confirm before overwriting something
alias df="df -h"      # human-readable sizes
alias du="du -h"      # human-readable sizes
alias free="free -m"  # human-readable sizes
alias ll="ls -l"      # detailed file list
alias la="ls -lA"     # detailed file list with hidden files
alias wh="which -aS"  # Informative version of which
alias svim="sudo vim" # edit protected files with vim

# When interactively starting vim, execute the vim-singleton function to avoid
# starting multiple vim instances.
alias vim='vim-singleton'

# Better LS sorting
#  - Collate listings so dot files are listed first
#  - Colorize the list
#  - Classify files (such as executables with a *)
#  - always show sizes in human readable formats
alias ls="LC_COLLATE=C ls --group-directories-first --color=auto --classify -h"

# Server the current directory over port 8000 using python
alias serve="python3 -m http.server"

# Better path echo
alias epath='echo -e ${PATH//:/\\n}'
