# Do nothing if not running interactively
[ -z "$PS1" ] && return

# Nice looking ps1 prompt (that tells me what system im on)
PS1='[\[\e[0;31m\]$(hostname)/\[\e[0m\]\[\e[0;34m\]${PWD##*/}/\[\e[0m\]]> '

# Bash options
shopt -s cdspell        # autocorrects cd misspellings
shopt -s checkwinsize   # update the value of LINES and COLUMNS after each command if altered
shopt -s cmdhist        # save multi-line commands in history as single line
shopt -s dotglob        # include dotfiles in pathname expansion
shopt -s expand_aliases # expand aliases
shopt -s extglob        # enable extended pattern-matching features
shopt -s histreedit     # Add failed commands to the bash history
shopt -s autocd         # Autocd

export HISTSIZE=1000
export HISTFILE="$XDG_CACHE_HOME/bash_history"
export HISTCONTROL=ignorespace:erasedups
export EDITOR=vim
export PAGER=less

# Make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

source "$XDG_CONFIG_HOME/bash/aliases"

# Source all extra functions
for f in $XDG_CONFIG_HOME/bash/functions.d/*; do source "$f"; done

# Source in all completions
for f in $XDG_CONFIG_HOME/bash/completion.d/*; do source "$f"; done

# Setup dircolors
eval $(dircolors "$XDG_CONFIG_HOME/bash/dircolors")
