#!/usr/bin/env bash

# This file is used to validate that common setup procedures have already been
# completed. Other config groups typically override this, since by default I do
# not have any required setup

export BASHRC_NOT_READY=0

# Ensure bash-preexec. Needed for atuin
if [ ! -f "$XDG_CONFIG_HOME/bash/bash-preexec" ]; then
	curl \
		-s https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh \
		-o "$XDG_CONFIG_HOME/bash/bash-preexec"
fi
