#!/bin/bash

export PATH="$HOME/.local/bin:$PATH"

# Set the systemd-style DBUS address
export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export  XDG_CACHE_HOME="$HOME/.cache"
export   XDG_DATA_HOME="$HOME/.local/share"

# Set the session ssh-agent socket path (If it's not set)
[ -z "$SSH_AUTH_SOCK" ] && export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent"

# Look for terminfo files under data
[ -d "$XDG_DATA_HOME/terminfo" ] && export TERMINFO="$XDG_DATA_HOME/terminfo"

# Set path to inputrc configuration
export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"

# Specify vimrc path
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/config.vim" | source $MYVIMRC'

# Ack configuration
if hash ack 2>/dev/null
then
    export ACKRC="$XDG_CONFIG_HOME/ack/ackrc"
    export ACK_PAGER_COLOR="less -x4SRFX"
fi

# Always install ruby gems local to the user
if hash gem 2>/dev/null
then
    export GEMRC="$XDG_CONFIG_HOME/gemrc/config"
    export GEM_HOME="$HOME/.local/lib/ruby/gems/$(ruby -e 'puts RbConfig::CONFIG["ruby_version"]')"
    export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem/specs"
    export PATH="$PATH:$GEM_HOME/bin"
fi

# nodejs's NPM tool configuration
if hash npm 2>/dev/null
then
    export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
    export PATH="$PATH:$HOME/.local/lib/nodejs/bin"
fi

hash gpg 2>/dev/null && export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
hash hg  2>/dev/null && export  HGRCPATH="$XDG_CONFIG_HOME/hg/config"

hash vagrant 2>/dev/null && export VAGRANT_HOME="$XDG_DATA_HOME/vagrant"

# Less history file location
export LESSHISTFILE="$XDG_CACHE_HOME/less_history"
