#!/usr/bin/env bash

# Set the systemd-style DBUS address
export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export  XDG_CACHE_HOME="$HOME/.cache"
export   XDG_DATA_HOME="$HOME/.local/share"

export PATH="$HOME/.local/bin:$XDG_CONFIG_HOME/bash/bin:$PATH"

# Look for terminfo files under data
[ -d "$XDG_DATA_HOME/terminfo" ] && export TERMINFO="$XDG_DATA_HOME/terminfo"

# Set path to inputrc configuration
export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"

# Specify vimrc path
# shellcheck disable=SC2016
export VIMCONFIG="$XDG_CONFIG_HOME/vim"
export VIMINIT='let $MYVIMRC="$VIMCONFIG/config.vim" | source $MYVIMRC'

# Ack configuration
if hash ack 2>/dev/null
then
  export ACKRC="$XDG_CONFIG_HOME/ack/ackrc"
  export ACK_PAGER_COLOR="less -x4SRFX"
fi

# Always install ruby gems local to the user
if hash gem 2>/dev/null
then
  export GEMRC="$XDG_CONFIG_HOME/gemrc/config"
  export GEM_HOME="$HOME/.local/lib/ruby/gems/$(ruby -e 'puts RbConfig::CONFIG["ruby_version"]')"
  export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem/specs"
  export PATH="$PATH:$GEM_HOME/bin"
fi

# Cocopods
if hash pod 2>/dev/null
then
  export CP_HOME_DIR="$XDG_DATA_HOME/cocoapods"
fi

if hash node 2>/dev/null
then
  export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
fi

# nodejs's NPM tool configuration
if hash npm 2>/dev/null
then
  export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
  export NPM_CONFIG_DEVDIR="$XDG_CACHE_HOME/node-gyp"
  export PATH="$PATH:$HOME/.local/lib/nodejs/bin"
fi

# Don't overrwrite an already configured GOPATH
if hash go 2>/dev/null && [ -z "${GOPATH+1}" ]
then
  export GOPATH="$HOME/.local/lib/go"
  export GO111MODULE=on
  export PATH="$PATH:$GOPATH/bin"
fi

if hash python 2>/dev/null
then
  # Disable python bytecode generation
  export PYTHONDONTWRITEBYTECODE=1

  # Configure poetry
  export POETRY_HOME="$HOME/.local/lib/poetry"
  export PATH="$PATH:$POETRY_HOME/bin"
fi

if hash aws 2>/dev/null
then
  export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"
  export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
fi

if hash redis-cli 2>/dev/null
then
  export REDISCLI_HISTFILE="$XDG_DATA_HOME/rediscli_history"
fi

if hash pod 2>/dev/null
then
  export CP_HOME_DIR="$XDG_CONFIG_HOME/cocopods"
  export CP_REPOS_DIR="$XDG_DATA_HOME/cocopods/repos"
  export CP_TEMPLATES_DIR="$XDG_DATA_HOME/cocopods/templates"
fi

if hash "$XDG_DATA_HOME/cargo/bin/rustc" 2>/dev/null
then
  export CARGO_HOME="$XDG_DATA_HOME/cargo"
  export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
  export PATH="$PATH:$CARGO_HOME/bin"
fi

hash pass    2>/dev/null && export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
hash vagrant 2>/dev/null && export       VAGRANT_HOME="$XDG_DATA_HOME/vagrant"

hash travis  2>/dev/null && export TRAVIS_CONFIG_PATH="$XDG_CONFIG_HOME/travis"
hash http    2>/dev/null && export  HTTPIE_CONFIG_DIR="$XDG_CONFIG_HOME/httpie"
hash ansible 2>/dev/null && export     ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/config.ini"
hash docker  2>/dev/null && export      DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
hash gpg     2>/dev/null && export          GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
hash hg      2>/dev/null && export           HGRCPATH="$XDG_CONFIG_HOME/hg/config"
hash wget    2>/dev/null && export             WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
hash psql    2>/dev/null && export             PSQLRC="$XDG_CONFIG_HOME/psql/psqlrc"

# Source shellcheck configuration
hash shellcheck 2>/dev/null && source "$XDG_CONFIG_HOME/bash/shellcheck"

# Less history file and key file
export LESSHISTFILE="$XDG_CACHE_HOME/less_history"
export LESSKEY="$XDG_CONFIG_HOME/less/keyfile.bin"

# Don't add quotes when using ls
export QUOTING_STYLE="literal"

# Stop annoying javascript servers from opening vim (due to react-dev-utils)
export REACT_EDITOR=false

# Include environment configurations from DATA_HOME
if [ -d "$XDG_DATA_HOME/environment.d" ]
then
  for f in "$XDG_DATA_HOME/environment.d/"*; do source "$f"; done
fi
