#!/usr/bin/env bash

hash fzf 2>/dev/null || return

export FZF_DEFAULT_OPTS='--prompt="› " --pointer="›" --marker="›"'
export FZF_DEFAULT_COMMAND='rg --files --hidden'
export FZF_CTRL_T_COMMAND="fd --type f --follow --hidden"

# Load completions
if [ -d "/usr/share/fzf" ]; then
	source "/usr/share/fzf/key-bindings.bash"
fi
