#!/usr/bin/env bash

hash fzf 2>/dev/null || return

source "$(cache-cmd brew --prefix fzf)/shell/completion.bash"
source "$(cache-cmd brew --prefix fzf)/shell/key-bindings.bash"

export FZF_DEFAULT_OPTS='--prompt="› " --pointer="›" --marker="›"'

export FZF_DEFAULT_COMMAND='rg --files --hidden'
export FZF_CTRL_T_COMMAND="fd --type f --follow --hidden"
