#!/bin/bash

# Include brew binaries
export PATH="$(brew --prefix)/bin:$PATH"

# Include GNU coreutil overrides when running interactively
[ -n "$PS1" ] && export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
