#!/usr/bin/sh
# Start programs for an X session

fork() { (setsid "$@" & )}

# Restore wallpaper
fork /usr/bin/nitrogen --restore

# Hide the mouse during typing
fork /usr/bin/unclutter

# X11 windowing compositor
fork /usr/bin/compton --config "${XDG_CONFIG_HOME}/compton/compton.conf"

# Clipboard management
fork /usr/bin/xcmenu

# Global hotkeys
fork /usr/bin/sxhkd

# Window managment
exec /usr/bin/bspwm
