#!/usr/bin/sh
# Start programs for an X session

fork() { (setsid "$@" & )}

# Restore wallpaper
fork /usr/bin/nitrogen --restore

# Hide the mouse during typing
fork /usr/bin/unclutter

# X11 windowing compositor
fork /usr/bin/compton --config "${XDG_CONFIG_HOME}/compton/compton.conf"

# Easy on the eyes
fork redshift

# Clipboard management
fork /usr/bin/xcmenu

# Global hotkeys
fork /usr/bin/sxhkd \
 -c ${XDG_CONFIG_HOME}/sxhkd/common.sxhkdrc \
 -c ${XDG_CONFIG_HOME}/sxhkd/bspwm.sxhkdrc

# Window managment
exec /usr/bin/bspwm
