set nocompatible

" Follow XDG directory specifications
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
set directory=$XDG_CACHE_HOME/vim
set viminfo+=n$XDG_CACHE_HOME/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$XDG_CONFIG_HOME/vim/bundle/vundle

" Load in vundle
filetype off
call vundle#rc("$XDG_CONFIG_HOME/vim/bundle")

" Let vundle manage itself
Bundle 'gmarik/vundle'

" Enable sensible options that should always be set
Bundle 'tpope/vim-sensible'

" Load Vundles
Bundle 'kien/ctrlp.vim'
Bundle 'itchyny/lightline.vim'
Bundle 'altercation/vim-colors-solarized'
Bundle 'w0ng/vim-hybrid'
Bundle 'godlygeek/tabular'
Bundle 'vim-scripts/AutoComplPop'
Bundle 'ervandew/supertab'
Bundle 'juvenn/mustache.vim'
Bundle 'ciaranm/detectindent'
Bundle 'tpope/vim-rsi.git'
Bundle 'tpope/vim-surround'

" Don't wrap visually wrap lines
set nowrap

" Show line numbers
set number

" Don't show mode (--INSERT--, etc)
set noshowmode

" Ignore cache type files
set wildignore+=*/cache/*,*.sassc

" Show some nonprintable characters
set list
set listchars-=eol

" Setup color schemes
silent! colorscheme hybrid
set cursorline

" Tabs configurations
set noexpandtab
set tabstop=4
set shiftwidth=4
set smartindent

" Turn off annoying backup files
set nobackup
set nowritebackup
set noswapfile

" Be a little more leniant about case sensitivity
set ignorecase
set infercase
set smartcase

" Add a way to write a file as sudo
cmap w!! w !sudo tee > /dev/null %

" Remap Ctrl+C to be the same as escape without telling us to use :q to quit
nnoremap <C-c> <silent> <ESC>

" Audo detect indent for all files
:autocmd BufReadPost * :DetectIndent

" Enable spell checking on git commits
au BufNewFile,BufRead COMMIT_EDITMSG setlocal spell

" md files should be markdown files
au BufNewFile,BufRead *.md set filetype=markdown
au BufRead,BufNewFile Vagrantfile set filetype=ruby
