#!/bin/bash

export PATH="$HOME/.local/bin:$PATH"

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export  XDG_CACHE_HOME="$HOME/.cache"
export   XDG_DATA_HOME="$HOME/.local/share"

# Set path to inputrc configuration
export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"

# Set the session ssh-agent socket path (If it's not set)
[ -z "$SSH_AUTH_SOCK" ] && export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent"

# Specify many application config paths
hash gimp       2>/dev/null && export GIMP2_DIRECTORY="$XDG_CONFIG_HOME/gimp-2.8"
hash virtualbox 2>/dev/null && export  VBOX_USER_HOME="$XDG_CONFIG_HOME/virtualbox"
[ -e /etc/gtk-2.0/gtkrc ]   && export   GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
hash mplayer    2>/dev/null && export    MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
hash vagrant    2>/dev/null && export    VAGRANT_HOME="$XDG_CONFIG_HOME/vagrant"
hash vim        2>/dev/null && export         VIMINIT='let $MYVIMRC="$HOME/.config/vim/vimrc" | source $MYVIMRC'

# Look for terminfo files under data
[ -d "$XDG_DATA_HOME/terminfo" ] && export TERMINFO="$XDG_DATA_HOME/terminfo"

# History file locations
hash mysql 2>/dev/null && export MYSQL_HISTFILE="$XDG_CACHE_HOME/mysql_history"
hash less  2>/dev/null && export   LESSHISTFILE="$XDG_CACHE_HOME/less_history"

# OpenGL NVIDIA shader cache directory
[ -e /usr/lib/modprobe.d/nvidia.conf ] && export __GL_SHADER_DISK_CACHE_PATH="$XDG_CACHE_HOME"

# Put chromiums cache in /tmp for better performance
hash chromium 2>/dev/null && export CHROMIUM_USER_FLAGS="--disk-cache-dir=/tmp/chrome-cache --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so"
