tap "evanpurkhiser/personal"
tap "homebrew/cask-fonts"
tap "1password/tap"

cask "1password"
cask "alacritty"
cask "discord"
cask "figma"
cask "google-chrome"
cask "hammerspoon"
cask "karabiner-elements"
cask "notion"
cask "numi"
cask "sip"
cask "pixelsnap"
cask "raycast"
cask "slack"
cask "tailscale"
cask "telegram"
cask "font-caskaydia-cove-nerd-font"
cask "1password-cli"
cask "obsidian"

# Basic terminal stuff
brew "atuin"
brew "bash"
brew "bash-completion@2"
brew "coreutils"
brew "vivid"

# Used to allow sudo via touch ID in tmux. Will be automatically configured by
# platform-osx/bash/functions.d/sudo
brew "pam-reattach"

# Terminal window management
brew "tmux"

# Tooling
brew "entr"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "htop"
brew "imagemagick"
brew "jq"
brew "jsonnet"
brew "lsd"
brew "neovim"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "tree"
brew "wget"

# Languages, runtimes, compilers
brew "cmake"
brew "go"
brew "node"
brew "python"
brew "ruby"
brew "sqlite"

# Dependency management
brew "pyenv"
brew "volta"
brew "direnv"
brew "yarn"
