#!/usr/bin/env bash

source "$DOTS_SOURCE/base/bash/environment"

# Reconfigure a number of hotkeys
#
# Useful resources for this
#
#  - https://krypted.com/mac-os-x/defaults-symbolichotkeys/
#  - https://apple.stackexchange.com/questions/201816/how-do-i-change-mission-control-shortcuts-from-the-command-line

rm -f "$HOME/Library/Preferences/com.apple.symbolichotkeys.plist"
ln -sf "$XDG_CONFIG_HOME/macos/com.apple.symbolichotkeys.plist" \
	"$HOME/Library/Preferences/com.apple.symbolichotkeys.plist"

# Apply keyboard changes, the defaults read is needed to ensure the cache is
# primed, then activateSettings does the magic
defaults read com.apple.symbolichotkeys.plist >/dev/null
/System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings -u
