name: check
on: [push]

jobs:
  check:
    name: simple-setup (no dependencies)
    runs-on: macos-latest
    strategy:
      matrix:
        profile: [home, work]
    steps:
      - uses: actions/checkout@v2

      - name: Install dotfiles
        env:
          TMP_DOTS: ${{ runner.temp }}/etc
        run: |
          mkdir -p $TMP_DOTS
          cp -r . $TMP_DOTS
          cd $TMP_DOTS

          source ./init
          dots config use ${{ matrix.profile }}
          dots config active
          dots install -v
